export const INITIAL_PLACES = [
  {
    id: 'place-1',
    name: '광화문 광장 (Gwanghwamun Square)',
    category: 'plaza',
    categoryLabel: '야외 응원',
    address: '서울특별시 종로구 세종대로 172',
    region: 'gwanghwamun',
    regionLabel: '광화문/종로',
    latitude: 37.5716,
    longitude: 126.9769,
    x: 50, // Central-ish map coordinates
    y: 35,
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deceeaf7?auto=format&fit=crop&w=600&q=80',
    atmosphereTags: ['미친 응원 분위기', '붉은악마 공식응원', '초대형 전광판', '야외 응원', '애국심 폭발'],
    crowdLevel: 'critical',
    crowdLabel: '🔥 현시각 인원 포화 (미터 폭발)',
    cheerIntensity: 98,
    screenSize: '500인치 초호화 야외 미디어월',
    reservationRequired: false,
    soloFriendly: true,
    instagramUrl: 'https://www.instagram.com/explore/tags/광화문광장/',
    naverMapUrl: 'https://map.naver.com/v5/search/광화문광장',
    description: '대한민국 축구 국가대표팀 응원의 상징! 붉은악마 공식 길거리 응원이 주최되는 성지입니다. 수만 명의 인파와 함께 심장이 울리는 우렁찬 드럼 소리, 연기, 환성을 온몸으로 즐겨보세요! 혼자 가셔도 1초 만에 어깨동무하고 함께 뛰게 됩니다.',
    realtimeReactions: {
      fireCount: 342,
      cheerCount: 810,
      noSeatCount: 45,
      goingCount: 1205
    },
    approved: true,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString()
  },
  {
    id: 'place-2',
    name: '홍대 레드 피치 스포츠펍 (Red Pitch)',
    category: 'pub',
    categoryLabel: '스포츠 펍',
    address: '서울특별시 마포구 와우산로19길 21 2층',
    region: 'hongdae',
    regionLabel: '홍대/신촌',
    latitude: 37.5512,
    longitude: 126.9224,
    x: 25, // West-ish
    y: 42,
    imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=600&q=80',
    atmosphereTags: ['축덕 많음', '대형 스크린 3개', '영국 펍 바이브', '예약 불가 (선착순)', '맥주 무제한'],
    crowdLevel: 'high',
    crowdLabel: '🍺 만석 임박 (스탠딩만 대기)',
    cheerIntensity: 91,
    screenSize: '180인치 프로젝터 및 전방향 UHD TV 4대',
    reservationRequired: false,
    soloFriendly: true,
    instagramUrl: 'https://www.instagram.com/explore/tags/스포츠펍/',
    naverMapUrl: 'https://map.naver.com/v5/search/홍대스포츠펍',
    description: '홍대 정문 인근 축덕들의 아지트! 해외 리그 경기부터 대한민국 국가대표 매치까지 전방향 사운드로 송출합니다. 붉은 조명과 네온 사인, 벽면 가득한 유니폼 액자가 스포츠 열기를 뜨겁게 더해줍니다. 축구 지식이 해박한 사장님이 매 경기 이벤트를 제안합니다.',
    realtimeReactions: {
      fireCount: 156,
      cheerCount: 290,
      noSeatCount: 38,
      goingCount: 420
    },
    approved: true,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString()
  },
  {
    id: 'place-3',
    name: '강남 골든 골 스크린 아레나',
    category: 'cinema',
    categoryLabel: '대형 스크린',
    address: '서울특별시 강남구 테헤란로 156 지하1층',
    region: 'gangnam',
    regionLabel: '강남/역삼',
    latitude: 37.5002,
    longitude: 127.0362,
    x: 72, // South East-ish
    y: 75,
    imageUrl: 'https://images.unsplash.com/photo-1486286701208-1d58e9338026?auto=format&fit=crop&w=600&q=80',
    atmosphereTags: ['웅장한 사운드', '400인치 LED 대형', '예약 필수', '에어컨 빵빵', '안락한 대형 소파'],
    crowdLevel: 'high',
    crowdLabel: '📺 전석 매진 (사전 예약자 전용)',
    cheerIntensity: 89,
    screenSize: '가로 8m 초대형 4K UHD LED 패널 마운트',
    reservationRequired: true,
    soloFriendly: false,
    instagramUrl: 'https://www.instagram.com/explore/tags/강남핫플/',
    naverMapUrl: 'https://map.naver.com/v5/search/강남스포츠바',
    description: '최강 화질과 음향으로 월드컵을 감상하고 싶다면 무조건 여기! 콘서트장 수준의 베이스 스피커 라인업으로 애국가 가창부터 중계진의 샤우팅까지 온몸으로 진동을 느낄 수 있습니다. 쾌적하게 좌석을 배정받아 치맥 세트와 함께 편안히 응원하세요.',
    realtimeReactions: {
      fireCount: 89,
      cheerCount: 172,
      noSeatCount: 94,
      goingCount: 128
    },
    approved: true,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString()
  },
  {
    id: 'place-4',
    name: '이태원 골목대장 루프탑 타번',
    category: 'lounge',
    categoryLabel: '라운지/루프탑',
    address: '서울특별시 용산구 이태원로27가길 12 3층',
    region: 'itaewon',
    regionLabel: '이태원/용산',
    latitude: 37.5348,
    longitude: 126.9934,
    x: 52, // South Center
    y: 54,
    imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=600&q=80',
    atmosphereTags: ['루프탑 응원', '힙한 바이브', '외국어 응원', '혼술 환영', '칵테일 축제'],
    crowdLevel: 'moderate',
    crowdLabel: '✨ 여유로움 (일부 테이블 남음)',
    cheerIntensity: 78,
    screenSize: '250인치 야외 프로젝터 스크린',
    reservationRequired: false,
    soloFriendly: true,
    instagramUrl: 'https://www.instagram.com/explore/tags/이태원루프탑/',
    naverMapUrl: 'https://map.naver.com/v5/search/이태원루프탑바',
    description: '이태원의 야경과 시원한 바람 속에서 전세계 팬들과 함께 하이파이브하며 응원하는 루프탑 라운지! 다양한 다국적 메뉴와 수제 칵테일을 들고 골이 들어갈 때마다 에너제틱하게 환호하는 다문화적 바이브입니다. 혼자 와서 친구 먹기 딱 좋습니다.',
    realtimeReactions: {
      fireCount: 74,
      cheerCount: 110,
      noSeatCount: 12,
      goingCount: 180
    },
    approved: true,
    createdAt: new Date(Date.now() - 86400000).toISOString()
  },
  {
    id: 'place-5',
    name: '신촌 로하통닭 & 치맥 스타디움',
    category: 'chicken',
    categoryLabel: '치킨집/호프',
    address: '서울특별시 마포구 백범로 22 1층',
    region: 'hongdae',
    regionLabel: '홍대/신촌',
    latitude: 37.5505,
    longitude: 126.9366,
    x: 32, // Shinchon (West Center)
    y: 44,
    imageUrl: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=600&q=80',
    atmosphereTags: ['치맥의 성지', '소리 질러도 안 혼남', '친근한 이모님', '동네 축덕 아지트'],
    crowdLevel: 'high',
    crowdLabel: '🍗 북적북적 (합석 추천)',
    cheerIntensity: 85,
    screenSize: '150인치 벽걸이 TV 및 3대 멀티 스크린',
    reservationRequired: false,
    soloFriendly: true,
    instagramUrl: 'https://www.instagram.com/explore/tags/치맥/',
    naverMapUrl: 'https://map.naver.com/v5/search/신촌치킨집',
    description: '전국 가마솥 통닭 장인 바이브와 축구 사랑 이모님의 환상 콜라보! 테이블마다 손잡고 한국 국가대표팀을 위해 악을 쓰며 목이 터져라 응원합니다. 이모님의 골 축하 무료 생맥주 서비스 이벤트도 종종 발동되는 진국 치킨집입니다.',
    realtimeReactions: {
      fireCount: 98,
      cheerCount: 215,
      noSeatCount: 17,
      goingCount: 220
    },
    approved: true,
    createdAt: new Date(Date.now() - 43200000).toISOString()
  },
  {
    id: 'place-6',
    name: '잠실 백호랑이 태극 옥돔포차',
    category: 'pub',
    categoryLabel: '스포츠 펍',
    address: '서울특별시 송파구 올림픽로12길 18 1층',
    region: 'jamsil',
    regionLabel: '잠실/송파',
    latitude: 37.5113,
    longitude: 127.0805,
    x: 88, // East
    y: 68,
    imageUrl: 'https://images.unsplash.com/photo-1436076863939-06870fe779c2?auto=format&fit=crop&w=600&q=80',
    atmosphereTags: ['조용하게 감상 가능', '안주가 예술', '맥덕들 추천', '대형 TV 완비'],
    crowdLevel: 'moderate',
    crowdLabel: '✨ 평온 (여유로운 치맥)',
    cheerIntensity: 72,
    screenSize: '85인치 UHD 스포츠 라이브 TV',
    reservationRequired: false,
    soloFriendly: true,
    instagramUrl: 'https://www.instagram.com/explore/tags/잠실맛집/',
    naverMapUrl: 'https://map.naver.com/v5/search/잠실포차',
    description: '너무 밀집된 인파의 소음에서 벗어나, 퀄리티 높은 수제 안주 and 기분 좋은 맥주를 마시며 편안히 축구를 지켜볼 수 있는 전통 포차 스타일 장소입니다. 동네 단골들이 축구 유니폼을 걸치고 도손도순 모여 진정성 있게 칭찬하고 분석하며 봅니다.',
    realtimeReactions: {
      fireCount: 35,
      cheerCount: 82,
      noSeatCount: 3,
      goingCount: 95
    },
    approved: true,
    createdAt: new Date(Date.now() - 172800000).toISOString()
  },
  {
    id: 'place-7',
    name: '낭만오지',
    category: 'pub',
    categoryLabel: '스포츠 펍',
    address: '서울 마포구 고산길 17',
    region: 'hongdae',
    regionLabel: '홍대/신촌',
    latitude: 37.5545,
    longitude: 126.9392,
    lat: 37.5545,
    lng: 126.9392,
    district: '신촌',
    vibe: '대학생 응원 분위기',
    screen: '대형스크린',
    screenSize: '대형스크린',
    cheering_style: '캐주얼 응원형',
    x: 33,
    y: 43,
    imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=600&q=80',
    atmosphereTags: ['대학생 응원 분위기', '대형스크린', '캐주얼 응원형', '신촌 핫플', '안주가 핵맛'],
    crowdLevel: 'moderate',
    crowdLabel: '✨ 여유로움 (시원한 공간)',
    cheerIntensity: 82,
    reservationRequired: false,
    soloFriendly: true,
    instagramUrl: 'https://www.instagram.com/explore/tags/신촌낭만오지/',
    naverMapUrl: 'https://map.naver.com/v5/search/%EC%8B%A0%EC%B3%8A%20%EB%82%AC%EB%A7%8C%EC%98%A4%EC%A7%80',
    description: '신촌 대학가에 위치한 낭만적인 응원 아지트입니다. 대형스크린을 완비하여 친구 및 과 동기들과 캐주얼하게 치맥 한잔 전골 한 그릇 나누며 편하게 국가대표 응원전을 가질 수 있는 안락한 요리 주점입니다.',
    realtimeReactions: {
      fireCount: 42,
      cheerCount: 89,
      noSeatCount: 4,
      goingCount: 110
    },
    approved: true,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString()
  },
  {
    id: 'place-8',
    name: '만선호프',
    category: 'chicken',
    categoryLabel: '치킨집/호프',
    address: '서울 마포구 와우산로17길 15 1층, 2층',
    region: 'hongdae',
    regionLabel: '홍대/신촌',
    latitude: 37.55013,
    longitude: 126.92134,
    lat: 37.55013,
    lng: 126.92134,
    district: '홍대',
    vibe: '시끌벅적 단체응원형',
    screen: 'TV 다수',
    screenSize: 'TV 다수',
    cheering_style: '떼창형',
    x: 26,
    y: 41,
    imageUrl: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=600&q=80',
    atmosphereTags: ['시끌벅적 단체응원형', 'TV 다수', '떼창형', '홍대 야장 감성', '만선 포차'],
    crowdLevel: 'critical',
    crowdLabel: '🔥 현시각 인원 포화 (야외 스탠딩 발생)',
    cheerIntensity: 96,
    reservationRequired: false,
    soloFriendly: true,
    instagramUrl: 'https://www.instagram.com/explore/tags/홍대만선호프/',
    naverMapUrl: 'https://map.naver.com/v5/search/%ED%99%8D%EB%8C%80%EB%A7%8C%EC%84%A0%ED%98%B8%ED%94%84',
    description: '마포구 홍대 어울마당로 삼거리포차 골목 인근에 우뚝 선 만선호프입니다. 야외 테라스 문을 활짝 개방해 시원함을 자랑하며, 스포츠 매치 시 실내외 다수의 고출력 TV 스크린을 보며 다 함께 소리 높여 우렁찬 떼창을 벌이는 단체 응원 전초기지입니다.',
    realtimeReactions: {
      fireCount: 210,
      cheerCount: 489,
      noSeatCount: 41,
      goingCount: 750
    },
    approved: true,
    createdAt: new Date(Date.now() - 43200000).toISOString()
  },
  {
    id: 'place-9',
    name: '썬더치킨',
    category: 'chicken',
    categoryLabel: '치킨집/호프',
    address: '서울 서대문구 연세로11길 20 1층',
    region: 'hongdae',
    regionLabel: '홍대/신촌',
    latitude: 37.5587,
    longitude: 126.9329,
    lat: 37.5587,
    lng: 126.9329,
    district: '신촌',
    vibe: '대학생 단체응원형',
    screen: 'TV 중계형',
    screenSize: 'TV 중계형',
    cheering_style: '캐주얼 응원형',
    x: 31,
    y: 40,
    imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=600&q=80',
    atmosphereTags: ['대학생 단체응원형', 'TV 중계형', '캐주얼 응원형', '치맥의 성지', '신촌 핫플'],
    crowdLevel: 'high',
    crowdLabel: '🍺 북적임 (스탠딩/만석)',
    cheerIntensity: 88,
    reservationRequired: false,
    soloFriendly: true,
    instagramUrl: 'https://www.instagram.com/explore/tags/신촌썬더치킨/',
    naverMapUrl: 'https://map.naver.com/v5/search/%EC%8B%A0%EC%B3%8A%20%EC%8D%AC%EB%8D%94%EC%B9%90%ED%82%A8',
    description: '서대문구 신촌 연세로11길 대학가 한복판의 썬더치킨입니다. 축구 경기가 있는 날이면 대학생 전사들과 서포터즈들이 가득 모여 치맥을 뜯으며 우렁찬 목소리로 뜨거운 캐주얼 응원전을 펼치는 아지트입니다!',
    realtimeReactions: {
      fireCount: 56,
      cheerCount: 124,
      noSeatCount: 15,
      goingCount: 220
    },
    approved: true,
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString()
  }
];

export const CATEGORY_DETAILS = {
  all: { label: '전체', color: 'bg-zinc-800 text-zinc-100' },
  pub: { label: '스포츠 펍', color: 'bg-emerald-950/80 text-emerald-300 border-emerald-500/30' },
  chicken: { label: '치킨집/호프', color: 'bg-amber-950/80 text-amber-300 border-amber-500/30' },
  plaza: { label: '야외 응원', color: 'bg-red-950/80 text-red-300 border-red-500/30' },
  cinema: { label: '대형 스크린', color: 'bg-cyan-950/80 text-cyan-300 border-cyan-500/30' },
  lounge: { label: '라운지/루프탑', color: 'bg-purple-950/80 text-purple-300 border-purple-500/30' },
};

export const CROWD_DETAILS = {
  critical: { label: '🔥 포화 (인원수 폭발)', color: 'text-rose-500 bg-rose-500/10 border-rose-500/30' },
  high: { label: '🍺 북적임 (스탠딩/만석)', color: 'text-amber-500 bg-amber-500/10 border-amber-500/30' },
  moderate: { label: '✨ 여유 (즐거운 분위기)', color: 'text-emerald-500 bg-emerald-500/10 border-emerald-500/30' },
  chill: { label: '👤 차분 (조용한 분석파)', color: 'text-sky-500 bg-sky-500/10 border-sky-500/30' },
};

export const REGIONS = [
  { value: 'all', label: '전체 서울' },
  { value: 'gwanghwamun', label: '광화문/종로' },
  { value: 'hongdae', label: '홍대/신촌' },
  { value: 'gangnam', label: '강남/역삼' },
  { value: 'itaewon', label: '이태원/용산' },
  { value: 'jamsil', label: '잠실/송파' }
];

export const ATMOSPHERE_TAGS_POOL = [
  '미친 응원 분위기',
  '붉은악마 공식응원',
  '축덕 많음',
  '대형 스크린 3개',
  '초대형 전광판',
  '영국 펍 바이브',
  '치맥의 성지',
  '소리 질러도 안 혼남',
  '루프탑 응원',
  '힙한 바이브',
  '외국어 응원',
  '조용하게 보기 가능',
  '혼자가도 안 어색',
  '웅장한 사운드',
  '에어컨 빵빵',
  '사장님이 국가대표 팬',
  '400인치 LED 대형',
  '예약 필수',
  '동네 축덕 아지트',
  '맥덕들 추천'
],
{
  id: 1,
  name: "신촌 낭만오지",
  address: "서울 마포구 고산길 17",
  screenType: "빔프로젝터",
  naverMapUrl: "https://naver.me/5r9z7UxJ"
},

{
  id: 2,
  name: "신촌 썬더치킨",
  address: "서울 서대문구 연세로11길 20 1층",
  screenType: "빔프로젝터",
  naverMapUrl: "https://naver.me/FTXDlTC9"
},
{
  id: 3,
  name: "신촌 뉴타운",
  address: "서울 서대문구 연세로12길 27",
  screenType: "TV 다수",
  naverMapUrl: "https://naver.me/IGJyfK7B"
},

{
  id: 4,
  name: "홍대 만선호프",
  address: "서울 마포구 와우산로17길 15 1층, 2층",
  screenType: "빔프로젝터",
  naverMapUrl: "https://naver.me/xq3drtjR"
},

{
  id: 5,
  name: "신촌 오퍼스",
  address: "서울 서대문구 연세로7길 18 2층",
  screenType: "빔프로젝터",
  naverMapUrl: "https://naver.me/Gipd4Lqn"
}
